### ISSUE TITLE
Deleting and setting variables in "on quit" event causes a small FREEZE

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1036]
I have this skript:

```
on quit:
  if player does not have permission "skript.perm.supporter" or "skript.perm.developer":
	make player execute command "/ch leave s"
```

When enabled, this causes a tiny server freeze the moment a player disconnects from the server. When disabled there is no freeze at all.

Timings (FULL):
https://timings.aikar.co/?id=c82862b8809f49e69ce8c20519d1fbc3#timings
Timings (Screenshot, part where player left the server):
https://image.ibb.co/iKwTZw/firefox_2017_12_29_23_20_21.png

**I am running PaperSpigot:**
This server is running Paper version git-Paper-1266 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Skript:**
Enabling Skript v2.2-dev32c

**Comment by bensku** [comment]
Interesting. Either checking permission or executing a command takes too long. It could be Skript issue, but it could also be your code. Where does /ch command come from?

**Comment by Blueyescat** [comment]
Trying to check permissions and execute a command **on quit** shouldn't be a problem right? Also i think the title is incorrect i can't see any variable.

**Comment by bensku** [comment]
It is not a problem, *except* if the permission check or command execution take a long time. Which may of course happen.

**Comment by bloggy** [comment]
The mentioned code indeed is the reason for the mini freeze when player logs out.
I fixed it with this code:

```
	# --- kick all "normal" players from support channel
	if player does not have permission "skript.perm.supporter" or "skript.perm.developer":
		make console execute command "/ch kick support %player%"	
```

The command /ch is from HeroChat (Plugin).

**Comment by bensku** [comment]
I do wonder why HeroChat causes this. But still not a Skript bug.
