### ISSUE TITLE
Sounds Not Work.

### ISSUE THREAD

**Issue by UzumakiYT** [bensku/Skript#1076]
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! [Skript] Severe Error:
[02:58:39 ERROR]: #!#! Could not load test.sk
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Something went horribly wrong with Skript.
[02:58:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:58:39 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[02:58:39 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[02:58:39 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[02:58:39 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[02:58:39 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Stack trace:
[02:58:39 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for visualeffect
[02:58:39 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1788)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1755)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1503)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1476)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:450)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[02:58:39 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:444)
[02:58:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[02:58:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[02:58:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[02:58:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:58:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:58:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:58:39 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Version Information:
[02:58:39 ERROR]: #!#!   Skript: 2.2-dev32d
[02:58:39 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[02:58:39 ERROR]: #!#!   Minecraft: 1.8.8
[02:58:39 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[02:58:39 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Running CraftBukkit: false
[02:58:39 ERROR]: #!#! Running Spigot (or compatible): true
[02:58:39 ERROR]: #!#! Running Paper (or compatible): false
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Current node: play sound "LEVEL_UP" with volume 100 and pitch 100 for player (test.sk, line 3)
[02:58:39 ERROR]: #!#! Current item: null
[02:58:39 ERROR]: #!#! Thread: Server thread
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! Language: english
[02:58:39 ERROR]: #!#! Link parse mode: DISABLED
[02:58:39 ERROR]: #!#!
[02:58:39 ERROR]: #!#! End of Error.
[02:58:39 ERROR]: #!#!
[02:58:39 INFO]: [Skript] All scripts loaded without errors.
[02:58:39 INFO]: [Skript] Loaded 1 script with a total of 0 triggers and 0 commands in 0.02 seconds
[02:58:39 INFO]: [Skript] Finished loading.

**Comment by Snow-Pyon** [comment]
Does this happen in 1
9+? If it's a 1.8 only error I may not fix it as it isn't supported.

**Comment by UzumakiYT** [comment]
yea but since dev32d was made to run on 1.8.8, this should be fixed.

**Comment by Snow-Pyon** [comment]
Please read the update notes, it says that 1.8.8 is still not supported, therefore you mau not expect any kind of fix for that versions unless someone makes a PR for it.

**Comment by UzumakiYT** [comment]
ok.

**Comment by TheBentoBox** [comment]
Unless I'm mistaken, this is actually not a vanilla Skript effect. The [vanilla `play sound` syntax](http://bensku.github.io/Skript/effects#EffPlaySound) requires a location to be passed in after the pitch at which the sound will be played. So you'll need to contact the developer of whatever addon adds this specific version of the syntax.

**Comment by Snow-Pyon** [comment]
Let me correct you, Skript thought the user was trying to execute the effect for showing visual effects. Now, you may wonder, *Why does it do that if the syntax doesn't match?*, it does that because in 1.8.8 the visual effect type is unregistered, that means anything after play could match because there is no classinfo registered to be matched.

Tagging @Pikachu here as he was the one who made the PR for this, could you possibly make a PR to also disable this effect and not just the type? So we can avoid further issues with anything that has play at the beginning of the syntax if the user is on 1.8.8.

**Comment by Pikachu920** [comment]
i will look into it

**Comment by UzumakiYT** [comment]
Thanks @Pikachu920

**Comment by UzumakiYT** [comment]
ps. skellet,skrayfall sounds are also broken.(for 1.8.8).

**Comment by TheBentoBox** [comment]
I see, thanks @Snow-Pyon, I should've been more patient! Since there is an issue of sorts at work here I'll reopen. Feel free to close once this is resolved.

**Comment by Pikachu920** [comment]
it should be noted that sounds are also broken on early 1.9 versions. I just forgot to report it, i'll try to fix that too.

**Comment by Pikachu920** [comment]
I opened a PR to fix this

**Comment by MoneyAlpha** [comment]
I'm getting the same error.

**Comment by Pikachu920** [comment]
@TheBentoBox this is now resolved, just pending release. Anyone with this issue can download the fix now from skript-build if they like
