### ISSUE TITLE
on rightclick on villager (bug)

### ISSUE THREAD

**Issue by tuanjr** [bensku/Skript#131]
i have skript like this:

```
on right click on a villager:
    message "&cVillager trade is disable" to the player
    cancel event  
```

but, player can by pass by hold something in left-hand (1,9 feature, press F)

**Comment by bensku** [comment]
Oops, I thought I had fixed this.

**Comment by tuanjr** [comment]
and this skript:
`#4 Anti Spawner Change via Egg
on rightclick on a monster spawner:
    player's tool is a spawn egg
    cancel event`
player can by pass, hold spawn egg, press F, left click.

**Comment by tuanjr** [comment]
and this skript won't work:
```
on right click on a armor stand:
    cancel event
```
pkayer still can put item in to armor stand

**Comment by bensku** [comment]
The last one is just lacking armor stand support, not really bug. Others are bugs indeed, and need fixing soon.

**Comment by tuanjr** [comment]
Do you have plan to support armor stand? please support it.

**Comment by JKGamerxD** [comment]
MundoSk support it:
```
[on] armor stand (interact|manipulate)

player #The player who touched the armor stand
event-entity #The armor stand
player's tool #The item being put on
event-item #The item being take off
event-slot #The slot who is touched (helmet, chestplate, leggings, boots)

[on] armor stand place

event-entity #The armor stand
```

**Comment by bensku** [comment]
Fixed the bug with mob spawners. I was unable to reproduce the one with villagers, though.

Test script (no pseudocode) would help for that.

**Comment by tuanjr** [comment]
@bensku 
bug with spawner still NOT fixed!
i use:
- dev19 version
- paperspigot 1.9.2
with this skript, player still can change spawner with spawner egg, just press F to change hand.
```
#4 Anti Spawner Change via Egg
on rightclick on a monster spawner:
    player's tool is a spawn egg
    cancel event
```

**Comment by bensku** [comment]
Uh, PaperSpigot... Well, I might have made a mistake, will check when I have time.

If this works just fine, I won't start debugging on PaperSpigot. More important things to do.

**Comment by TheBentoBox** [comment]
Long resolved and no response.
