### ISSUE TITLE
Ampersand-driven color codes and messages containing angled brackets no longer work in dev-26b

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#465]
Hello

Attempting to send any chat message in dev-26 seems to cause a severe error. At first I thought it was only happening with messages containing angled brackets (which would make sense with how your JSON parsing works), but I quickly realized it's happening with any message, even when I have no addons installed or scripts loaded.

## Example Tests
![image](https://cloud.githubusercontent.com/assets/6902229/24772730/7d9b3fdc-1ae0-11e7-8cc2-e136b2030e24.png)
As you can see, first I tried sending just the plain text "example". No error, but nothing comes through. Then, I tried sending an expression, and it did throw an internal error, again with nothing coming through. [This is my console](https://pastebin.com/eKqhQeWv) when trying those two things.

## Setups
- Skript dev26
- Latest Spigot 1.11.2 build
- No addons, no scripts loaded
- [Setup screenshot](https://gyazo.com/3edc68836804b85373960d226fd3f3e4)

**Comment by bensku** [comment]
Wait a second. That method definitely exists on my test server (Paper 1.11.2)... Hmm, will need to check with Spigot.

**Comment by RezzedUp** [comment]
Can't even send messages to the console either...

```javascript
on script load:
    send "Broken." to console
```

```sql
>sk reload broken
[15:49:44 INFO]: [Skript] Reloading broken.sk...
[15:49:44 WARN]: Unexpected exception while parsing console command "sk reload broken"
org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev26
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-b4417b8-a552117]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-b4417b8-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.jar:git-Spigot-b4417b8-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.jar:git-Spigot-b4417b8-a552117]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.jar:git-Spigot-b4417b8-a552117]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-b4417b8-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-b4417b8-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-b4417b8-a552117]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.command.CommandSender.sendMessage([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.events.EvtScript.register(EvtScript.java:61) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:518) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:269) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b4417b8-a552117]
        ... 8 more
```
Please take errors like this into consideration before adding features that are already available in vanilla Skript. :)

**Comment by bensku** [comment]
The funny thing is that this works on my dev environment. Why? Because Paper adds this method *and* that addition is not documented outside of raw diff files in their Github repo. On the other hand, I have to build Skript against Paper API for timings API...

Luckily, there exists normal Spigot API for situations like this. It is just a bit clunky plus even less documented. Fix ETA tomorrow.

About errors like these... Well, they are pre-releases for a reason. It means that there are broken features (docs, for example, until now) and also that something might break. I should, perhaps, have a testing run for each release with some Skript users... Maybe.

**Comment by RezzedUp** [comment]
> About errors like these... Well, they are pre-releases for a reason. It means that there are broken features (docs, for example, until now) and also that something might break.

Yes, of course. I would never expect a pre-release to be flawless. 

What I *am* saying is, the only reason this error exists is because you've added something that's already 100% doable in vanilla Skript. So, please consider current options and how they work (such as the following: 'Who uses these features? What server software do they run?') before releasing new features that essentially replace them.

> I should, perhaps, have a testing run for each release with some Skript users... Maybe.

That would be ideal, but I don't necessarily blame you for releasing this update as a pre-release (where we're supposed to find errors & report back).

**Comment by TheBentoBox** [comment]
I think you could maybe do with mentioning on the repo or on each release that you build against Paper if you don't have that mentioned somewhere already, but otherwise I don't think it's really a big deal. As you said, these are pre-releases for a reason. I always test these on a local server as opposed to my live one, so issues like this never have an actual negative effect on me or my server.

**Comment by bensku** [comment]
This is first release that I built and tested against Paper. I also tested that it doesn't outright crash, but *not* after chat changes; I didn't see any reasons why it wouldn't work. A mistake, bad, bad mistake. The thing that I tested with Spigot - timings - does disable itself cleanly on Spigot, as I tested and expected.

About features that I consider available in Vanilla Skript... JSON chat sounds, and is, really advanced feature on code level. However, it makes no sense that scripter needs to install additional dependencies (yes, that includes scripts) for a feature that has been there since Minecraft 1.7!

**Comment by bensku** [comment]
Fixed in dev26b, hopefully. @TheBentoBox please close this when you have checked that there are no further problems.

**Comment by TheBentoBox** [comment]
Checking now

**Comment by TheBentoBox** [comment]
Mostly works. The JSON stuff is working again and doesn't send me errors, and works find sending to console, but traditional color codes using ampersand no longer work unless you specify `colored` before the message. Skript color codes in angled brackets _do_ still work, but I assume this change isn't intentional as it breaks all scripts that use ampersand for color codes, making them all send the ampersands literally:

![image](https://cloud.githubusercontent.com/assets/6902229/24813615/b7511cda-1b9c-11e7-9564-d0fc770c5978.png)

It's actually convenient in a way, since you can easily send actual ampersands now without them being forcibly parsed since we get to specify when it's colored, but it should probably be fixed due to how many old scripts it will break.

**Comment by TheBentoBox** [comment]
Additionally, you can't send any messages that contain text within angled brackets anymore. This means you can't do stuff like send a custom usage for a command where you use angled brackets around arguments (e.g. `send "Usage: /tp <player>"` will now throw an internal error). This didn't used to happen, and is new with the JSON changes. [This is the console error that's given](https://pastebin.com/MrqJq46Q).

It seems like you're attempting to parse anything within angled brackets as JSON tags, when it should only be trying to parse actual JSON tags, and anything else should be sent as is.

**Comment by bensku** [comment]
Well, supporting &... I guess I'll have to. But Minecraft itself doesn't use two character color codes with JSON chat so it will be some kind of hack.

Hmm, the issue about attempting to parse everything... Very interesting, I though I fixed it already. But I guess there are more cases where it won't work.

**Comment by TheBentoBox** [comment]
While it's true that Minecraft doesn't technically support the color codes, something interesting I found is if you, for example, parse a tellraw console command with color codes in the text component, it will appropriately send it colored. What I mean is, if I log in and run this:

execute console command "/tellraw Mr_Simba {""text"":""&6Hello""}"

It actually will send it with gold text even though I'm not properly using the color JSON component. Something with how the formatting codes are parsed causes it to work anyways. I believe it's cause they're just replaced with the section sign, which Minecraft then uses itself for passing color codes even mid-line in JSON like that. 

Not sure if that helps you @bensku . I'd try the simple thing first though (using the Bukkit method to parse color codes in a message). You may be surprised to see that it just works immediately due to what I said above.

**Comment by bensku** [comment]
Allright, I'll try that first.

**Comment by bensku** [comment]
Should be fixed. I made ampersand color and formatting codes be just aliases for color tags. I also added a check that will check against invalid tags and show them as-is.

**Comment by TheBentoBox** [comment]
Awesome, will test it out for you now.

**Comment by TheBentoBox** [comment]
Still not working fully as intended, but this issue is starting to become muddled, and I don't think it should go through a ton of title changes.
